### ISSUE TITLE
how to exclude directories?

### ISSUE THREAD

**Issue by jots** [zeekay/bebop#5]
my ~/.bebop.coffee looks like:

```
module.exports =
  exclude: ["build", "old"]
  compilers:
    css: (src) ->
      "postcss -u autoprefixer -u rucksack-css #{src} -d build/"
```
it gaks with the exclude line in there.  How do I specify directories and files to exclude?

**Comment by zeekay** [comment]
It expects regexes, but would be good to automatically convert strings to regex.

**Comment by zeekay** [comment]
I'll add that in a subsequent version, I have a few changes coming soon.

**Comment by jots** [comment]
ah, regexes, that works.  thanks.  looking forward to the changes, I think bebop would be great as a general purpose app server :-)

**Comment by zeekay** [comment]
Yeah I think there is more I can do there for sure. Also interested in improving use as part of a static site/generated site/single-page apps.
